# Generated by Django 4.1.4 on 2022-12-15 10:02

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('usage_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', model_utils.fields.StatusField(choices=[('Активирована', 'Активирована'), ('Не активирована', 'Не активирована'), ('Просрочена', 'Просрочена')], default='Активирована', max_length=100, no_check_for_status=True)),
            ],
        ),
    ]
